# Generated by Django 4.0.2 on 2022-03-14 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customusermodel',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='customusermodel',
            unique_together={('email',)},
        ),
    ]
