# Generated by Django 4.0.2 on 2022-03-16 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_customusermodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='email_password',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
