# Generated by Django 4.0.2 on 2022-04-08 20:47

import Emailer.authentication.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_customusermodel_email_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[Emailer.authentication.validators.is_gmail_validator]),
        ),
    ]
