# Generated by Django 4.0.2 on 2022-04-15 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_customusermodel_email'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customusermodel',
            table='User',
        ),
    ]
