# Generated by Django 4.0.2 on 2022-02-20 09:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(5)])),
                ('message', models.TextField()),
                ('to', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(10)])),
                ('upload_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('upload_file', models.FileField(blank=True, null=True, upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
