# Generated by Django 4.0.2 on 2022-03-25 13:55

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('main', '0001_initial'), ('main', '0002_rename_to_email_receiver_email_date_receiver_group'), ('main', '0003_remove_email_user_alter_email_receiver'), ('main', '0004_preferences_remove_receiver_additional_data_and_more'), ('main', '0005_receiver_age_remove_receiver_preferences_and_more'), ('main', '0006_alter_preferences_name_remove_receiver_preferences_and_more'), ('main', '0007_rename_name_preferences_hobby_and_more'), ('main', '0008_remove_receiver_username'), ('main', '0009_alter_receiver_age'), ('main', '0010_alter_receiver_preferences'), ('main', '0011_remove_email_context_email_is_deleted_and_more'), ('main', '0012_remove_email_subject'), ('main', '0013_email_screenshot_email_template'), ('main', '0014_alter_email_template'), ('main', '0015_alter_email_template'), ('main', '0016_alter_email_template'), ('main', '0017_email_subject'), ('main', '0018_alter_email_subject'), ('main', '0019_rename_mail_receiver_email_alter_email_receiver_and_more'), ('main', '0020_alter_customtemplate_template_alter_email_screenshot'), ('main', '0021_remove_email_template'), ('main', '0022_email_template'), ('main', '0023_alter_email_date'), ('main', '0024_remove_customtemplate_is_global_template_and_more'), ('main', '0025_alter_email_screenshot'), ('main', '0026_alter_email_screenshot'), ('main', '0027_alter_email_screenshot'), ('main', '0028_alter_receiver_email')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.FileField(upload_to='template/')),
                ('name', models.CharField(default='Pavel', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Receiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.EmailField(max_length=254, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(blank=True, max_length=20, null=True)),
                ('last_name', models.CharField(blank=True, max_length=20, null=True)),
                ('age', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('receivers', models.ManyToManyField(to='main.Receiver')),
            ],
        ),
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hobby', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='receiver',
            name='preferences',
            field=models.ManyToManyField(blank=True, max_length=20, null=True, to='main.Preferences'),
        ),
        migrations.RenameField(
            model_name='receiver',
            old_name='mail',
            new_name='email',
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='receiver', to='main.receiver')),
                ('date', models.DateTimeField(auto_now=True, default=datetime.datetime(2022, 3, 19, 15, 52, 32, 380954))),
                ('is_deleted', models.BooleanField(default=False)),
                ('screenshot', models.URLField()),
                ('subject', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(5)])),
                ('template', models.ForeignKey(default=3, on_delete=django.db.models.deletion.DO_NOTHING, to='main.customtemplate')),
            ],
        ),
        migrations.AlterField(
            model_name='receiver',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
