# Generated by Django 4.0.2 on 2022-03-04 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_to_email_receiver_email_date_receiver_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='user',
        ),
        migrations.AlterField(
            model_name='email',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.receiver'),
        ),
    ]
