# Generated by Django 4.0.2 on 2022-02-20 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_customtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtemplate',
            name='is_global_template',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customtemplate',
            name='template',
            field=models.FileField(upload_to='templates/'),
        ),
    ]
