# Generated by Django 4.0.2 on 2022-03-29 14:45

import cloudinary.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_customtemplate_name_alter_email_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtemplate',
            name='thumbnail',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='receiver',
            name='age',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='receiver',
            name='first_name',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.MaxLengthValidator(20)]),
        ),
        migrations.AlterField(
            model_name='receiver',
            name='last_name',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.MaxLengthValidator(20)]),
        ),
    ]
