# Generated by Django 4.0.2 on 2022-03-30 14:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_customtemplate_thumbnail_alter_receiver_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiver',
            name='age',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
