# Generated by Django 4.0.2 on 2022-03-05 09:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_preferences_remove_receiver_additional_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiver',
            name='age',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(0)]),
        ),
        migrations.RemoveField(
            model_name='receiver',
            name='preferences',
        ),
        migrations.AddField(
            model_name='receiver',
            name='preferences',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
