# Generated by Django 4.0.2 on 2022-03-05 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_receiver_age_remove_receiver_preferences_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.RemoveField(
            model_name='receiver',
            name='preferences',
        ),
        migrations.AddField(
            model_name='receiver',
            name='preferences',
            field=models.ManyToManyField(blank=True, max_length=20, null=True, to='main.Preferences'),
        ),
    ]
