# Generated by Django 4.0.2 on 2022-03-05 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_preferences_name_remove_receiver_preferences_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preferences',
            old_name='name',
            new_name='hobby',
        ),
        migrations.RenameField(
            model_name='receiver',
            old_name='name',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='receiver',
            name='preferences',
            field=models.ManyToManyField(choices=[('Sports', 'Sports'), ('Work', 'Work'), ('Education', 'Education'), ('Leisure activities', 'Leisure activities')], max_length=20, to='main.Preferences'),
        ),
    ]
