# Generated by Django 4.0.2 on 2022-04-08 20:39

import Emailer.authentication.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_receiver_preferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiver',
            name='email',
            field=models.EmailField(max_length=254, validators=[Emailer.authentication.validators.is_gmail_validator]),
        ),
    ]
