# Generated by Django 4.0.2 on 2022-03-05 11:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_receiver_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiver',
            name='age',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
