# Generated by Django 4.0.2 on 2022-04-08 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_receiver_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiver',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
