# Generated by Django 4.0.2 on 2022-03-05 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_receiver_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiver',
            name='preferences',
            field=models.ManyToManyField(max_length=20, to='main.Preferences'),
        ),
    ]
