# Generated by Django 4.0.2 on 2022-04-11 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_receiver_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customtemplate',
            name='template',
            field=models.FileField(upload_to='templates/email-templates'),
        ),
        migrations.AlterField(
            model_name='email',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
