# Generated by Django 4.0.2 on 2022-03-10 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_receiver_preferences'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='context',
        ),
        migrations.AddField(
            model_name='email',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='email',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.receiver'),
        ),
    ]
