# Generated by Django 4.0.2 on 2022-03-10 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_email_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='email',
            name='template',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='main.customtemplate'),
        ),
    ]
