# Generated by Django 4.0.2 on 2022-03-10 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_email_screenshot_email_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.customtemplate'),
        ),
    ]
