# Generated by Django 4.0.2 on 2022-03-15 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_email_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receiver',
            old_name='mail',
            new_name='email',
        ),
        migrations.AlterField(
            model_name='email',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='receiver', to='main.receiver'),
        ),
        migrations.AlterField(
            model_name='receiver',
            name='preferences',
            field=models.ManyToManyField(blank=True, max_length=20, null=True, to='main.Preferences'),
        ),
    ]
