# Generated by Django 4.0.2 on 2022-03-16 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_rename_mail_receiver_email_alter_email_receiver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customtemplate',
            name='template',
            field=models.FileField(upload_to='template/'),
        ),
        migrations.AlterField(
            model_name='email',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='screenshots/'),
        ),
    ]
