# Generated by Django 4.0.2 on 2022-03-17 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_customtemplate_template_alter_email_screenshot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='template',
        ),
    ]
