# Generated by Django 4.0.2 on 2022-03-18 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_remove_email_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='template',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.DO_NOTHING, to='main.customtemplate'),
            preserve_default=False,
        ),
    ]
