# Generated by Django 4.0.2 on 2022-03-19 13:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_email_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='date',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2022, 3, 19, 15, 52, 32, 380954)),
            preserve_default=False,
        ),
    ]
