# Generated by Django 4.0.2 on 2022-03-23 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_email_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customtemplate',
            name='is_global_template',
        ),
        migrations.RemoveField(
            model_name='customtemplate',
            name='user',
        ),
        migrations.AddField(
            model_name='customtemplate',
            name='name',
            field=models.CharField(default='Pavel', max_length=20),
            preserve_default=False,
        ),
    ]
