# Generated by Django 4.0.2 on 2022-03-25 02:06

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_remove_customtemplate_is_global_template_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='screenshot',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
