# Generated by Django 4.0.2 on 2022-03-25 02:08

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_email_screenshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='screenshot',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
